#!/bin/sh

echo 'Creating TIP table in CDB'

sqlplus C\#\#MYUSER/mypassword@//localhost:1521/ORCLCDB  <<- EOF

  CREATE TABLE TIP
  (
    TIP_ID NUMBER(20) NOT NULL,
    TIP_TITLE VARCHAR2(125 CHAR),
    TIP_ABSTRACT VARCHAR2(1500 CHAR),
    TIP_DESCRIPTION CLOB,
    SITE_ID NUMBER(5) NOT NULL,
    LAST_UPD_DATE DATE NOT NULL,
    LAST_UPD_BY VARCHAR2(50 CHAR),
    OBSOLETE_FLAG VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL,
    SUPPLEMENTAL LOG GROUP GGS_199631 (TIP_ID,SITE_ID) ALWAYS
  );

  ALTER TABLE TIP ADD (
    CONSTRAINT TIP_PK
    PRIMARY KEY
    (TIP_ID, SITE_ID));

EOF

